version: '3.8'
services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    links:
      - db

  db:
    image: mysql:8.0.20
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_DATABASE: pthttm  
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    ports:
      - "32000:3306"

  web:
    image: nginx:1.22.0-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app
